# Primeiro vamos dar um nome para o workflow
name: Workflow com dependecia de Jobs falho

# escolhendo os eventos (gatilhos) de disparo de Job
on: 
  push:
    branches: [main, master, develop, hotfix]
  pull_request:
    branches: [main, master, develop, hotfix]

# agora iremso descever os passos do Workflow
jobs:
  job1:
    name: Primeiro Fluxo
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1
        run: echo "Rodando o primeiro passo do deploy."
      - name: Passo 2
        run: echo "Rodando o segundo passo do deploy."
      - name: Passo 3
        run: echo "Rodando o terceiro passo do deploy."

  job2:
    name: Segundo Fluxo
    runs-on: ubuntu-latest
    steps:
      - name: Passo 4
        run: echo "Rodando o quarto passo do deploy."
      - name: Passo 5
        run: echo "Rodando o quinto passo do deploy."
      - name: Passo 6
        run: echo "Rodando o sexto passo do deploy."

  Job3:
    name: Terceiro Fluxo
    runs-on: ubuntu-latest
    steps:
      - name: Passo 7
        run: echo "Rodando o sétimo passo do deploy."
      - name: Passo 8
        run: echo "Rodando o oitavo passo do deploy."
      - name: Passo 9
        run: echo "Rodando o nono passo do deploy."
